# ==============================================================================
# WORKFLOW GITHUB ACTIONS POUR L'ANALYSE BRVM (MIS À JOUR)
# ==============================================================================
name: Analyse Financière BRVM Quotidienne

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # CORRECTION : Installation simplifiée pour utiliser les versions par défaut
    # de l'environnement GitHub Actions et éviter les conflits.
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install blinker==1.6.2 selenium-wire gspread google-auth-oauthlib google-auth-httplib2 beautifulsoup4 requests python-docx pandas openpyxl pdfplumber google-generativeai

    - name: Run BRVM Financial Analysis Script
      env:
        GSPREAD_SERVICE_ACCOUNT: ${{ secrets.GSPREAD_SERVICE_ACCOUNT }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: python main.py

    - name: Upload Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: execution-artifacts
        path: |
          ./*.docx
          ./debug_*.png
          ./debug_*.html
