# ==============================================================================
# WORKFLOW GITHUB ACTIONS POUR L'ANALYSE BRVM (VERSION FINALE STABLE)
# ==============================================================================
name: Analyse Financière BRVM Quotidienne

on:
  schedule:
    # S'exécute tous les jours à 7h UTC
    - cron: '0 7 * * *'
  # Permet une exécution manuelle depuis l'interface GitHub
  workflow_dispatch:

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Étape stable pour installer Chrome et son pilote de manière compatible
    - name: Setup Chrome for Selenium
      uses: browser-actions/setup-chrome@latest

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install blinker==1.6.2 selenium-wire gspread google-auth-oauthlib google-auth-httplib2 beautifulsoup4 requests python-docx pandas openpyxl pdfplumber google-generativeai

    - name: Run BRVM Financial Analysis Script
      env:
        GSPREAD_SERVICE_ACCOUNT: ${{ secrets.GSPREAD_SERVICE_ACCOUNT }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: python main.py

    # Étape pour sauvegarder le rapport Word généré comme un "artifact"
    - name: Upload Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Rapport-Analyse-BRVM
        path: |
          ./*.docx
